### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by simon-p-r** [zaggino/z-schema#116]
Hi

Just trying to make a pull request to add some handling for registering formats and this error occurred when running npm install.

````Shell

D:\Modules\z-schema>npm install
/
> z-schema@3.11.0 prepublish D:\Modules\z-schema
> grunt

Running "copy:dist" (copy) task


Running "lineending:dist" (lineending) task

Running "jshint:all" (jshint) task
>> 16 files lint free.

Running "jscs:src" (jscs) task
>> 15 files without code style errors.

Running "jasmine_node:src" (jasmine_node) task
Module load hook: transform [D:\Modules\z-schema\src\ZSchema.js]
Module load hook: transform [D:\Modules\z-schema\src\Polyfills.js]
Module load hook: transform [D:\Modules\z-schema\src\Report.js]
Module load hook: transform [D:\Modules\z-schema\src\Errors.js]
Module load hook: transform [D:\Modules\z-schema\src\Utils.js]
Module load hook: transform [D:\Modules\z-schema\src\FormatValidators.js]
Module load hook: transform [D:\Modules\z-schema\src\JsonValidation.js]
Module load hook: transform [D:\Modules\z-schema\src\SchemaCache.js]
Module load hook: transform [D:\Modules\z-schema\src\SchemaCompilation.js]
Module load hook: transform [D:\Modules\z-schema\src\SchemaValidation.js]
Exception loading: D:\Modules\z-schema\test\spec\JsonSchemaTestSuiteSpec.js
{ [Error: Cannot find module '../jsonSchemaTestSuite/tests/draft4/additionalItems.json'] code: 'MODULE_NOT_FOUND' }
>> Failed to execute "jasmine.executeSpecsInFolder": Error: Cannot find module '../jsonSchemaTestSuite/tests/draft4/additionalItems.json'
>>     at Function.Module._resolveFilename (module.js:336:15)
>>     at Function.Module._load (module.js:278:25)
>>     at Module.require (module.js:365:17)
>>     at require (module.js:384:17)
>>     at Object.<anonymous> (D:\Modules\z-schema\test\spec\JsonSchemaTestSuiteSpec.js:17:5)
>>     at Module._compile (module.js:460:26)
>>     at Object.Module._extensions..js (module.js:478:10)
>>     at Object.Module._extensions.(anonymous function) [as .js] (D:\Modules\z-schema\node_modules\grunt-jasmine-node-coverage\node_modules\istanbul\lib\hook.js:109:37)
>>     at Module.load (module.js:355:32)
>>     at Function.Module._load (module.js:310:12)

Running "browserify:src" (browserify) task

Running "browserify:test" (browserify) task
>> Error: Cannot find module '../jsonSchemaTestSuite/remotes/subSchemas.json' from ````Shell
'D:\Modules\z-schema\test\spec'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "node" "C:\\Users\\Simon\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE
npm ERR! z-schema@3.11.0 prepublish: `grunt`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the z-schema@3.11.0 prepublish script 'grunt'.
npm ERR! This is most likely a problem with the z-schema package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt
npm ERR! You can get their info via:
npm ERR!     npm owner ls z-schema
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Modules\z-schema\npm-debug.log

**Comment by IvanGoncharov** [comment]
@simon-p-r You need to clone your repository recursively, see [here](https://github.com/zaggino/z-schema#development)

**Comment by simon-p-r** [comment]
Thanks @IvanGoncharov missed this in README
