### ISSUE TITLE
Exception when validate schema using cli

### ISSUE THREAD

**Issue by joetconcur** [zaggino/z-schema#97]
I was trying to validate a schema, which has references to another schema file, and receive the following exception. I suspect the references could not be resolved.
```
E:\_src\schema>z-schema myschema.json

TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (C:\Users\user01\AppData\Roaming\npm\node_modules\z-schema\bin\z-schema:91:59)
    at self.callback (C:\Users\user01\AppData\Roaming\npm\node_modules\z-schema\node_modules\request\request.js:344:22)
    at Request.emit (events.js:95:17)
    at Request.init (C:\Users\user01\AppData\Roaming\npm\node_modules\z-schema\node_modules\request\request.js:413:17)
    at new Request (C:\Users\user01\AppData\Roaming\npm\node_modules\z-schema\node_modules\request\request.js:264:8)
    at request (C:\Users\user01\AppData\Roaming\npm\node_modules\z-schema\node_modules\request\index.js:50:10)
    at C:\Users\user01\AppData\Roaming\npm\node_modules\z-schema\bin\z-schema:86:17
    at Array.forEach (native)
    at validate (C:\Users\user01\AppData\Roaming\npm\node_modules\z-schema\bin\z-schema:85:31)
    at validateWithAutomaticDownloads (C:\Users\user01\AppData\Roaming\npm\node_modules\z-schema\bin\z-schema:112:5)
```

**Comment by zaggino** [comment]
@joetconcur z-schema@3.6.2 was published to the registry, this is fixed so you should be able to see what the error really is

**Comment by joetconcur** [comment]
Thanks for the fast fix!
Quick question. If I want to reference to another schema file in the same directory,  what syntax do I use? The error I received was `[Error: Invalid URI "another-schema.json"]`

**Comment by zaggino** [comment]
That's currently not supported, but also not difficult to implement at all. I'll take a go at this after the weekend. Or submit a PR if you want @joetconcur

**Comment by zaggino** [comment]
@joetconcur can you try latest `3.7.0` ?

**Comment by joetconcur** [comment]
I just tried v3.7.1 and it worked awesome on the cli Thanks for all your help!
Now I will try the same using javascript in node js and will report back.
